AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation main template

Parameters:
  TemplateBucket:
    Type: String
    Description: The name of the S3 bucket containing the templates and scripts

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/example/auto-scaling-group/vpc.yaml"
  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/example/auto-scaling-group/alb.yaml"
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.PublicSubnet2Id
  ASGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/example/auto-scaling-group/asg.yaml"
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        ALBSecurityGroupId: !GetAtt ALBStack.Outputs.ALBSecurityGroup
        TargetGroup: !GetAtt ALBStack.Outputs.TargetGroup80
        AmiId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
  ASGPolicyAndAlarmStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/example/auto-scaling-group/asg-policy-and-alarm.yaml"
      Parameters:
        AutoScalingGroupName: !GetAtt ASGStack.Outputs.AutoScalingGroup
  ASGPolicyAndScheduleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/example/auto-scaling-group/asg-policy-and-schedule.yaml"
      Parameters:
        AutoScalingGroupName: !GetAtt ASGStack.Outputs.AutoScalingGroup
